spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB


springdoc:
  default-produces-media-type: application/json
  openapi:
    path: /api-docs

  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  servlet:
    context-path: /api/v1/
