pipeline {
  agent any

  environment {
    PROJECT_DIR = 'BackendPFE'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Clean Docker Containers') {
      steps {
        dir("${env.PROJECT_DIR}") {
          bat '''
            docker-compose down || echo "No containers to stop"
            docker rm -f mysql-sql-bsn mail-dev-bsn || echo "Containers already removed"
          '''
        }
      }
    }

    stage('Start MySQL and MailDev') {
      steps {
        dir("${env.PROJECT_DIR}") {
          bat 'docker-compose up -d'
        }
      }
    }

    stage('Build Project') {
      steps {
        dir("${env.PROJECT_DIR}") {
          bat 'mvnd clean package -DskipTests'

        }
      }
    }

   stage('SonarQube Analysis') {
  steps {
    withSonarQubeEnv('MySonarQubeFrontend') {
      dir("${env.PROJECT_DIR}") {
        bat """
          mvnd sonar:sonar ^
            -Dsonar.projectKey=com.PFE:BackendPFE ^
            -Dsonar.host.url=http://localhost:9000 ^
            -Dsonar.login=squ_751443ec224600759633b50839c067d88e44e9a2
        """
      }
    }
  }
}

stage('SonarQube Quality Gate') {
  steps {
    timeout(time: 2, unit: 'MINUTES') {
      waitForQualityGate abortPipeline: true
    }
  }
}

    stage('Stop Docker Services') {
      steps {
        dir("${env.PROJECT_DIR}") {
          bat 'docker-compose down'
        }
      }
    }
  }

  post {
    always {
      echo 'Pipeline terminé.'
    }
    success {
      echo 'Build réussi.'
    }
    failure {
      echo 'Build échoué.'
    }
  }
}
